version: '2'
services:
  httpd:
    build: httpd
    volumes:
      - ./httpd/public-html:/docroot/html
    links:
      - php
    ports:
      - 80:80
    restart: always
  php:
    image: php:5.6-fpm-alpine
    volumes:
      - ./httpd/public-html:/docroot/html
    restart: always

