backend:
  image: php:5.6-fpm-alpine
  restart: always
  volumes:
    - ./httpd/public-html:/docroot/html

frontend:
  build: httpd
  volumes:
    - ./httpd/public-html:/docroot/html
  links:
    - backend:php
  environment:
    - ENV_VAR1=some_value
  ports:
    - 80:80
  environment:
    - VAR1=value
  restart: always
