FROM centos/httpd-24-centos7
MAINTAINER  Gene Liverman <gene@technicalissues.us>

COPY ./conf.modules.d/ /opt/rh/httpd24/root/etc/httpd/conf.modules.d/
COPY ./conf.d/ /opt/rh/httpd24/root/etc/httpd/conf.d/

